# Environment-specific values for kube-prometheus-stack in STAGING
kube-prometheus-stack:
  # Prometheus configuration for STAGING
  prometheus:
    prometheusSpec:
      retention: 30d
      retentionSize: "20GB"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "default"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      
      # More restrictive monitoring in staging
      serviceMonitorNamespaceSelector:
        matchLabels:
          monitoring: "enabled"
      ruleNamespaceSelector:
        matchLabels:
          monitoring: "enabled"
  
  # Grafana configuration for STAGING
  grafana:
    adminPassword: "stagingadmin123"
    persistence:
      size: 20Gi
    
    service:
      type: ClusterIP
    
    # Disable anonymous access in staging
    grafana.ini:
      auth.anonymous:
        enabled: false
  
  # Production-like AlertManager config
  alertmanager:
    alertmanagerSpec:
      retention: 168h  # 7 days
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "default"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
      
      # Add alert routing config
      config:
        global:
          smtp_smarthost: 'localhost:587'
        route:
          group_by: ['alertname']
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 1h
          receiver: 'web.hook'
        receivers:
        - name: 'web.hook'
          webhook_configs:
          - url: 'http://127.0.0.1:5001/'