# Environment-specific values for kube-prometheus-stack in STAGING
kube-prometheus-stack:
  # Prometheus configuration for STAGING
  prometheus:
    prometheusSpec:
      retention: 7d
      retentionSize: "3GB"
      resources:
        limits:
          cpu: 600m
          memory: 1.2Gi
        requests:
          cpu: 200m
          memory: 600Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 8Gi
      
      # More restrictive monitoring in staging
      serviceMonitorNamespaceSelector:
        matchLabels:
          monitoring: "enabled"
      ruleNamespaceSelector:
        matchLabels:
          monitoring: "enabled"
  
  # Grafana configuration for STAGING
  grafana:
    adminPassword: "stagingadmin123"
    resources:
      limits:
        cpu: 250m
        memory: 400Mi
      requests:
        cpu: 100m
        memory: 200Mi
    persistence:
      size: 3Gi
    
    service:
      type: ClusterIP
    
    # Disable anonymous access in staging
    grafana.ini:
      auth.anonymous:
        enabled: false
  
  # Production-like AlertManager config
  alertmanager:
    alertmanagerSpec:
      retention: 48h
      resources:
        limits:
          cpu: 100m
          memory: 150Mi
        requests:
          cpu: 50m
          memory: 75Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 3Gi
  
  # Resource limits for staging environment
  prometheusOperator:
    resources:
      limits:
        cpu: 150m
        memory: 200Mi
      requests:
        cpu: 75m
        memory: 100Mi
  
  # Node exporter resource limits
  nodeExporter:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  
  # Kube state metrics resource limits  
  kubeStateMetrics:
    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 75Mi
      
      # Add alert routing config
      config:
        global:
          smtp_smarthost: 'localhost:587'
        route:
          group_by: ['alertname']
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 1h
          receiver: 'web.hook'
        receivers:
        - name: 'web.hook'
          webhook_configs:
          - url: 'http://127.0.0.1:5001/'