replicaCount: 1

image:
  repository: ghcr.io/1979447992/microservice2
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: false

env: []
