apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules
type: application
version: 1.0.0
appVersion: "v0.68.0"
dependencies:
  - name: kube-prometheus-stack
    version: "51.2.0"
    repository: "https://prometheus-community.github.io/helm-charts"