# Default values for kube-prometheus-stack
# This is a YAML-formatted file.

kube-prometheus-stack:
  # Prometheus configuration
  prometheus:
    prometheusSpec:
      retention: 7d
      retentionSize: "2GB"
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      
      # Service discovery for microservices
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      ruleSelectorNilUsesHelmValues: false
      ruleSelector: {}
  
  # Grafana configuration
  grafana:
    enabled: true
    adminPassword: "admin123"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    persistence:
      enabled: true
      size: 2Gi
      storageClassName: "local-path"
    
    service:
      type: NodePort
      nodePort: 30080
    
    # Import dashboards for Spring Boot
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'spring-boot'
          orgId: 1
          folder: 'Spring Boot'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/spring-boot
    
    dashboards:
      spring-boot:
        spring-boot-dashboard:
          gnetId: 12900
          revision: 1
          datasource: Prometheus
  
  # AlertManager configuration
  alertmanager:
    alertmanagerSpec:
      retention: 24h
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
  
  # Node exporter (for node metrics)
  nodeExporter:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  
  # Kube state metrics
  kubeStateMetrics:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi