# ============================================================
# SIT 环境 ArgoCD 完整部署配置 (一键部署版本)
# ============================================================
# 
# 📝 学习说明:
# 这是 SIT 环境的完整 ArgoCD 部署配置文件
# 包含命名空间、完整RBAC权限、App of Apps应用
#
# 🔧 配置特点:
# - 使用 argocd-sit 命名空间实现环境隔离
# - 完整RBAC权限配置，确保一键部署成功
# - 无初始密码配置，使用ArgoCD随机生成密码
# - 真正的一键部署，无需额外配置
#
# 🚀 部署命令:
# kubectl apply -f app-of-apps.yaml
# kubectl apply -n argocd-sit -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# kubectl patch svc argocd-server -n argocd-sit -p '{"spec":{"type":"NodePort","ports":[{"port":80,"nodePort":30089}]}}'
# ============================================================

# 命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-sit
  labels:
    environment: sit
    app.kubernetes.io/name: argocd
---
# 完整集群权限 - 确保一键部署成功
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-sit
rules:
# 完整权限，确保ArgoCD能访问所有资源
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
# 非资源URL权限
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
# 集群权限绑定
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-sit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-sit
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-sit
---
# App of Apps应用 - 管理所有SIT环境应用
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-sit
  namespace: argocd-sit
  labels:
    environment: sit
    app.kubernetes.io/name: app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/1979447992/project-gitops-config.git
    targetRevision: sit
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
