apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/1979447992/project-gitops-config.git
    targetRevision: sit
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
