# ============================================================
# SIT 环境 ArgoCD 部署配置
# ============================================================
# 
# 📝 学习说明:
# 这个配置用于部署 SIT 环境的 ArgoCD 实例
# 使用标准 argocd 命名空间，但通过分支隔离确保环境独立
#
# 🔧 部署特点:
# - 标准的 argocd 命名空间
# - 不同的 NodePort 端口 (30089)
# - SIT 专属的管理员密码
# - 仅管理 SIT 环境的应用
#
# 🌟 分支隔离优势:
# - 每个分支包含完整的环境配置
# - 通过Git分支实现环境隔离
# - 标准化的命名空间管理
# ============================================================

apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    environment: sit
    app.kubernetes.io/name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  # Server configuration for SIT environment
  server:
    service:
      type: NodePort
      nodePort: 30089  # Different port from DEV ArgoCD (30080)
    grpc:
      ingress:
        enabled: false
    insecure: true
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi
  
  # Dex server (disabled for simplicity)
  dex:
    openShiftOAuth: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  
  # Repository server
  repo:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  
  # Application controller
  controller:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  
  # Redis configuration
  redis:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  
  # RBAC configuration for SIT environment only
  rbac:
    defaultPolicy: "role:readonly"
    policy: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      g, argocd-sit:admin, role:admin
    scopes: "[groups]"
---
# Initial admin password secret for SIT ArgoCD
apiVersion: v1
kind: Secret
metadata:
  name: argocd-initial-admin-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  password: c2l0YWRtaW4xMjM=  # sitadmin123 in base64