# ============================================================
# SIT 监控环境配置 - 已禁用
# ============================================================
# 
# 📝 学习说明:
# 这个文件包含了 SIT 环境的完整监控配置，包括:
# - Prometheus (指标收集)
# - Grafana (可视化面板)  
# - AlertManager (告警管理)
# - Node Exporter (节点监控)
# - Kube State Metrics (K8s状态监控)
#
# 🔧 如何启用:
# 1. 将此文件重命名为: kube-prometheus-stack-monitoring-sit.yaml
# 2. 确保 monitoring-sit 命名空间存在
# 3. ArgoCD 会自动检测并部署 SIT 监控环境
#
# 💡 配置差异 (相比DEV环境):
# - 更高的资源配置 (CPU/内存)
# - 更长的数据保留时间 (5天 vs 3天)  
# - SIT专属的告警规则配置
# - 不同的NodePort端口 (30081)
#
# ⚠️  当前状态: 已禁用 (节省集群资源)
# ============================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-monitoring-sit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/1979447992/project-gitops-config.git
    targetRevision: main
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - ../../environments/sit/kube-prometheus-stack-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true