# ============================================================
# SIT 环境 Microservice1 应用配置
# ============================================================
# 
# 📝 学习说明:
# 这是 SIT 环境专用的 microservice1 应用定义
# 完全独立于 DEV 环境，使用 sit 分支的配置
#
# 🔧 配置特点:
# - 部署到 microservice1-sit 命名空间
# - 使用 SIT 环境专用的 Helm values
# - 独立的资源管理和配置
# ============================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice1-sit
  namespace: argocd-sit
spec:
  project: default
  source:
    repoURL: https://github.com/1979447992/project-gitops-config.git
    targetRevision: sit
    path: charts/microservice1
    helm:
      valueFiles:
        - ../../environments/sit/microservice1-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservice1-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true