# Environment-specific values for kube-prometheus-stack in SIT
kube-prometheus-stack:
  # Prometheus configuration for SIT
  prometheus:
    service:
      type: NodePort
      nodePort: 30091
    prometheusSpec:
      retention: 5d
      retentionSize: "2GB"
      resources:
        limits:
          cpu: 800m
          memory: 1.5Gi
        requests:
          cpu: 300m
          memory: 768Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      
      # Allow scraping from all namespaces in sit
      serviceMonitorNamespaceSelector: {}
      ruleNamespaceSelector: {}
  
  # Grafana configuration for SIT
  grafana:
    adminPassword: "sitadmin123"
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 150Mi
    persistence:
      size: 2Gi
    
    service:
      type: NodePort
      nodePort: 30085
    
    # Disable anonymous access for sit environment
    grafana.ini:
      auth.anonymous:
        enabled: false
  
  # AlertManager for SIT
  alertmanager:
    service:
      type: NodePort
      nodePort: 30094
    alertmanagerSpec:
      retention: 24h
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
  
  # Resource limits for node exporter
  nodeExporter:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  
  # Resource limits for kube state metrics
  kubeStateMetrics:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi