# Environment-specific values for kube-prometheus-stack in SIT
kube-prometheus-stack:
  # Prometheus configuration for SIT
  prometheus:
    service:
      type: NodePort
      nodePort: 30091  # Different port for SIT
    prometheusSpec:
      retention: 5d
      retentionSize: "2GB"
      resources:
        limits:
          cpu: 400m
          memory: 768Mi
        requests:
          cpu: 150m
          memory: 384Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      
      # Monitoring specific namespaces in SIT
      serviceMonitorNamespaceSelector:
        matchNames:
        - microservice1-sit
        - microservice2-sit
        - monitoring-sit
      ruleNamespaceSelector:
        matchNames:
        - microservice1-sit
        - microservice2-sit
        - monitoring-sit
  
  # Grafana configuration for SIT
  grafana:
    adminPassword: "sitadmin123"
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 75m
        memory: 150Mi
    persistence:
      size: 2Gi
    
    service:
      type: NodePort
      nodePort: 30085
    
    # Limited anonymous access for SIT
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
        org_name: "SIT Environment"
    
    # SIT-specific datasource settings
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus-SIT
          type: prometheus
          url: http://kube-prometheus-stack-prometheus:9090
          access: proxy
          isDefault: false
  
  # AlertManager configuration for SIT
  alertmanager:
    service:
      type: NodePort
      nodePort: 30094  # Different port for SIT
    alertmanagerSpec:
      retention: 24h
      resources:
        limits:
          cpu: 75m
          memory: 96Mi
        requests:
          cpu: 35m
          memory: 48Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      
      # SIT-specific alert routing
      config:
        global:
          smtp_smarthost: 'localhost:587'
        route:
          group_by: ['alertname', 'environment']
          group_wait: 30s
          group_interval: 30s
          repeat_interval: 2h
          receiver: 'sit-webhook'
          routes:
          - match:
              severity: critical
            receiver: 'sit-critical'
        receivers:
        - name: 'sit-webhook'
          webhook_configs:
          - url: 'http://127.0.0.1:5002/'
            title: 'SIT Alert'
        - name: 'sit-critical'
          webhook_configs:
          - url: 'http://127.0.0.1:5002/critical'
            title: 'SIT Critical Alert'
  
  # Resource limits for SIT environment
  prometheusOperator:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  
  # Node exporter resource limits
  nodeExporter:
    resources:
      limits:
        cpu: 75m
        memory: 48Mi
      requests:
        cpu: 35m
        memory: 24Mi
  
  # Kube state metrics resource limits
  kubeStateMetrics:
    resources:
      limits:
        cpu: 75m
        memory: 96Mi
      requests:
        cpu: 35m
        memory: 48Mi