# Environment-specific values for kube-prometheus-stack in SIT
kube-prometheus-stack:
  # Prometheus configuration for SIT
  prometheus:
    prometheusSpec:
      retention: 15d
      retentionSize: "15GB"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "default"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 30Gi
      
      # Monitoring specific namespaces in SIT
      serviceMonitorNamespaceSelector:
        matchNames:
        - microservice1-sit
        - microservice2-sit
        - monitoring-sit
      ruleNamespaceSelector:
        matchNames:
        - microservice1-sit
        - microservice2-sit
        - monitoring-sit
  
  # Grafana configuration for SIT
  grafana:
    adminPassword: "sitadmin123"
    persistence:
      size: 10Gi
    
    service:
      type: NodePort
      nodePort: 30081
    
    # Limited anonymous access for SIT
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
        org_name: "SIT Environment"
    
    # SIT-specific datasource settings
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus-SIT
          type: prometheus
          url: http://kube-prometheus-stack-prometheus:9090
          access: proxy
          isDefault: true
  
  # AlertManager configuration for SIT
  alertmanager:
    alertmanagerSpec:
      retention: 48h  # 2 days
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "default"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      
      # SIT-specific alert routing
      config:
        global:
          smtp_smarthost: 'localhost:587'
        route:
          group_by: ['alertname', 'environment']
          group_wait: 30s
          group_interval: 30s
          repeat_interval: 2h
          receiver: 'sit-webhook'
          routes:
          - match:
              severity: critical
            receiver: 'sit-critical'
        receivers:
        - name: 'sit-webhook'
          webhook_configs:
          - url: 'http://127.0.0.1:5002/'
            title: 'SIT Alert'
        - name: 'sit-critical'
          webhook_configs:
          - url: 'http://127.0.0.1:5002/critical'
            title: 'SIT Critical Alert'
  
  # Resource limits for SIT environment
  prometheusOperator:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi