# ============================================================
# SIT 环境 App of Apps 配置
# ============================================================
# 
# 📝 学习说明:
# 这是 SIT 环境专用的 App of Apps 模式配置
# 只管理 SIT 环境相关的应用，完全独立于 DEV 环境
#
# 🔧 配置特点:
# - 仅从 sit 分支拉取配置
# - 部署到 argocd-sit 命名空间
# - 只管理 SIT 相关的应用定义
#
# 🌟 App of Apps 模式优势:
# - 统一管理多个应用的部署
# - 声明式配置，易于维护
# - 支持环境特定的应用组合
# ============================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sit-app-of-apps
  namespace: argocd-sit
spec:
  project: default
  source:
    repoURL: https://github.com/1979447992/project-gitops-config.git
    targetRevision: sit  # Only SIT branch
    path: argocd-sit/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true