# Environment-specific values for kube-prometheus-stack in DEV
kube-prometheus-stack:
  # Prometheus configuration for DEV
  prometheus:
    service:
      type: NodePort
      nodePort: 30090  # Port for DEV
    prometheusSpec:
      retention: 7d
      retentionSize: "3GB"
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 8Gi
      
      # Monitoring specific namespaces in DEV
      serviceMonitorNamespaceSelector:
        matchNames:
        - microservice1-dev
        - microservice2-dev
        - monitoring
      ruleNamespaceSelector:
        matchNames:
        - microservice1-dev
        - microservice2-dev
        - monitoring
  
  # Grafana configuration for DEV
  grafana:
    adminPassword: "devadmin123"
    resources:
      limits:
        cpu: 300m
        memory: 400Mi
      requests:
        cpu: 100m
        memory: 200Mi
    persistence:
      size: 3Gi
    
    service:
      type: NodePort
      nodePort: 30081
    
    # Full anonymous access for DEV
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Admin
        org_name: "DEV Environment"
    
    # DEV-specific datasource settings
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus-DEV
          type: prometheus
          url: http://kube-prometheus-stack-prometheus:9090
          access: proxy
          isDefault: true
  
  # AlertManager configuration for DEV
  alertmanager:
    service:
      type: NodePort
      nodePort: 30093  # Port for DEV
    alertmanagerSpec:
      retention: 24h
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 3Gi
      
      # DEV-specific alert routing
      config:
        global:
          smtp_smarthost: 'localhost:587'
        route:
          group_by: ['alertname', 'environment']
          group_wait: 10s
          group_interval: 5s
          repeat_interval: 1h
          receiver: 'dev-webhook'
          routes:
          - match:
              severity: critical
            receiver: 'dev-critical'
        receivers:
        - name: 'dev-webhook'
          webhook_configs:
          - url: 'http://127.0.0.1:5001/'
            title: 'DEV Alert'
        - name: 'dev-critical'
          webhook_configs:
          - url: 'http://127.0.0.1:5001/critical'
            title: 'DEV Critical Alert'
  
  # Resource limits for DEV environment
  prometheusOperator:
    resources:
      limits:
        cpu: 150m
        memory: 256Mi
      requests:
        cpu: 75m
        memory: 128Mi
  
  # Node exporter resource limits
  nodeExporter:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  
  # Kube state metrics resource limits
  kubeStateMetrics:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi