# Environment-specific values for kube-prometheus-stack in DEV
kube-prometheus-stack:
  # Prometheus configuration for DEV
  prometheus:
    service:
      type: NodePort
      nodePort: 30090
    prometheusSpec:
      retention: 3d
      retentionSize: "1GB"
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 3Gi
      
      # Allow scraping from all namespaces in dev
      serviceMonitorNamespaceSelector: {}
      ruleNamespaceSelector: {}
  
  # Grafana configuration for DEV
  grafana:
    adminPassword: "devadmin123"
    resources:
      limits:
        cpu: 150m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi
    persistence:
      size: 1Gi
    
    service:
      type: NodePort
      nodePort: 30081
    
    # Enable anonymous access for dev environment
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
  
  # Smaller resource requests for dev
  alertmanager:
    service:
      type: NodePort
      nodePort: 30093
    alertmanagerSpec:
      retention: 12h
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 25m
          memory: 32Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
  
  # Resource limits for node exporter
  nodeExporter:
    resources:
      limits:
        cpu: 50m
        memory: 32Mi
      requests:
        cpu: 25m
        memory: 16Mi
  
  # Resource limits for kube state metrics
  kubeStateMetrics:
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi