image:
  repository: ghcr.io/1979447992/microservice2
  tag: "dev-latest"
  pullPolicy: Always
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
service:
  type: ClusterIP
  port: 8080
env:
  - name: APP_ENVIRONMENT
    value: "DEV"

# Monitoring configuration for DEV
namespace: microservice2-dev
environment: dev